version: "3.8"

services:

  mongo:
    image: mongo:8.0.0-rc13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: GhjcnjGfhjkm12
    ports:
      - 27017:27017
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: GhjcnjGfhjkm12
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:GhjcnjGfhjkm12@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

